"""Versioned SFU rulebook, as data.

The YAML files in this package ARE the rulebook (CLAUDE.md non-negotiable #2:
gates, word lists, verb lists, KSA modifiers and restricted titles live in
versioned YAML, never hardcoded in logic). :mod:`.loader` is the only reader:
it validates them into frozen pydantic models and precompiles the regexes.

    from src.jd_core.rules import get_rules

    rules = get_rules()
    rules.thresholds.duties_max          # 5
    rules.scoring.grade_for(82.0)        # "B"

Bump ``version:`` in *every* YAML file together whenever a threshold, the
lexicon, the glossary, or the scoring changes — the loader rejects a split
version.
"""

from src.jd_core.rules.loader import (
    CONTENT_HASH_LENGTH,
    DEDUP_FILE,
    EMBEDDINGS_FILE,
    GENERAL_SECTION,
    HAY_BASE_LEVEL,
    QUALITY_FILE,
    REGISTER_FILE,
    REWRITE_FILE,
    RULE_FILES,
    SEGMENTATION_FILE,
    UNMAPPED,
    VERSION_SEPARATOR,
    WJQ_FILE,
    ActionVerbs,
    AuthoringGuard,
    BlockingRulesGate,
    Boilerplate,
    ClusterAlgorithm,
    ClusterRepresentativePolicy,
    ClusterTier,
    CodedTerms,
    Comparison,
    ConfigRef,
    DecisionProvenance,
    DecisionRegister,
    DecisionStatus,
    Dedup,
    DedupEdgeScope,
    DedupTextSource,
    Embeddings,
    ExactEdgeTopology,
    GatePolicy,
    GateSpec,
    GradeBand,
    GradeFloorGate,
    Harmonization,
    HaySignalRules,
    HRDecision,
    Markers,
    Patterns,
    PositionIdGrouping,
    Qualifications,
    QualityAuditRules,
    RestrictedTitle,
    Rewrite,
    RuleCatalog,
    RuleOwner,
    Rules,
    RulesError,
    RuleSpec,
    ScoreFloorGate,
    Scoring,
    Segmentation,
    SeverityFloorGate,
    SkillGroundingPolicy,
    TextNorm,
    Thresholds,
    Titles,
    TrivialExemption,
    Wjq,
    WjqIdField,
    WjqQualKind,
    WjqSection,
    assert_register_in_step,
    check_register,
    decision_surface,
    get_rules,
    live_value,
    load_rules,
    normalize_config_value,
    resolve_config_path,
)

# NOTE: `src.jd_core.rules.render` is deliberately NOT re-exported here. It is the
# register's *view* (and a `python -m` entry point the Makefile runs); importing it
# from this package would make `-m` re-execute an already-imported module. Import it
# directly: `from src.jd_core.rules.render import render_register`.

__all__ = [
    "CONTENT_HASH_LENGTH",
    "DEDUP_FILE",
    "EMBEDDINGS_FILE",
    "GENERAL_SECTION",
    "HAY_BASE_LEVEL",
    "REGISTER_FILE",
    "REWRITE_FILE",
    "RULE_FILES",
    "UNMAPPED",
    "VERSION_SEPARATOR",
    "WJQ_FILE",
    "ActionVerbs",
    "AuthoringGuard",
    "BlockingRulesGate",
    "Boilerplate",
    "ClusterAlgorithm",
    "ClusterRepresentativePolicy",
    "ClusterTier",
    "CodedTerms",
    "Comparison",
    "Dedup",
    "DedupEdgeScope",
    "DedupTextSource",
    "Embeddings",
    "ExactEdgeTopology",
    "ConfigRef",
    "PositionIdGrouping",
    "QUALITY_FILE",
    "QualityAuditRules",
    "SEGMENTATION_FILE",
    "Segmentation",
    "DecisionProvenance",
    "DecisionRegister",
    "DecisionStatus",
    "GatePolicy",
    "GateSpec",
    "GradeBand",
    "GradeFloorGate",
    "Harmonization",
    "HRDecision",
    "HaySignalRules",
    "Markers",
    "Patterns",
    "Qualifications",
    "RestrictedTitle",
    "Rewrite",
    "RuleCatalog",
    "RuleOwner",
    "RuleSpec",
    "Rules",
    "RulesError",
    "ScoreFloorGate",
    "Scoring",
    "SeverityFloorGate",
    "SkillGroundingPolicy",
    "TextNorm",
    "Thresholds",
    "Titles",
    "TrivialExemption",
    "Wjq",
    "WjqIdField",
    "WjqQualKind",
    "WjqSection",
    "assert_register_in_step",
    "check_register",
    "decision_surface",
    "get_rules",
    "live_value",
    "load_rules",
    "normalize_config_value",
    "resolve_config_path",
]
